# this is numpy code

In [1]:
import numpy as np 

In [2]:
myarr = np.array([3,6,8,9])

In [3]:
myarr

array([3, 6, 8, 9])

In [6]:
myarr[0]=45

In [7]:
myarr

array([45,  6,  8,  9])

# array creation

In [8]:
listarray = np.array([[1,2,3],[5,6,7],[0,3,2]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 3, 2]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng=np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,10)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.64418068e-293, 1.42419938e-306, 7.56603881e-307],
       [8.45603441e-307, 1.42417221e-306, 1.60219306e-306,
        6.23059726e-307, 1.06811422e-306, 1.42417221e-306],
       [1.37961641e-306, 6.23039694e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.69118787e-306, 1.20161526e-306, 6.23059726e-307,
        1.20161730e-306, 1.20161526e-306, 8.34451504e-308]])

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
ide.size

2025

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr = arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.shape

(99,)

In [34]:
x=[[1,2,3],[4,5,6],[4,6,4]]

In [35]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 4]])

In [37]:
ar.sum(axis=0)

array([ 9, 13, 13])

In [39]:
ar.sum(axis=1)

array([ 6, 15, 14])

In [40]:
ar.T

array([[1, 4, 4],
       [2, 5, 6],
       [3, 6, 4]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
4
6
4


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one = np.array([1,3,4,5,66,6])

In [48]:
one.argmax()

4

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 1, 2, 3, 5, 4], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 4]])

In [53]:
ar.argmin()

0

In [54]:
ar.min()

1

In [56]:
ar.argmax()

5

In [57]:
ar.argmax(axis=0)

array([1, 2, 1], dtype=int64)

In [58]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [59]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 4, 6, 4])

In [63]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [4],
       [6],
       [4]])

In [65]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 4, 6, 4])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 4]])

In [68]:
ar2=np.array([[1, 5, 3],
       [4, 5, 2],
       [4, 1, 4]])

In [69]:
ar2

array([[1, 5, 3],
       [4, 5, 2],
       [4, 1, 4]])

In [70]:
ar+ar2

array([[ 2,  7,  6],
       [ 8, 10,  8],
       [ 8,  7,  8]])

In [71]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [72]:
ar * ar2

array([[ 1, 10,  9],
       [16, 25, 12],
       [16,  6, 16]])

In [73]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.        , 2.44948974, 2.        ]])

In [75]:
ar.sum()

35

In [76]:
ar.max()

6

In [78]:
ar.min()

1

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 4]])

In [80]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 1], dtype=int64))

In [84]:
type(np.where(ar>5))

tuple

In [85]:
np.count_nonzero(ar)

9

In [87]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [88]:
ar[1,2]=0

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [4, 6, 4]])

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [91]:
import sys

In [96]:
py_ar = [0,4,55,2]

In [97]:
np_ar = np.array(py_ar)

In [98]:
sys.getsizeof(1) * len(py_ar)

112

In [99]:
np_ar.itemsize * np_ar.size

16